import { Hono, type Context, type Next } from "hono";
import { getCookie } from "hono/cookie";
import { verify } from "hono/jwt";
import type { Database } from "bun:sqlite";
import { createPermissionChecker } from "../auth/middleware";
import { AdminLayout, CrudTable, type Row } from "./views";
import { getErrorMessage } from "../../lib/cache";
import { Toast } from "./views";

const guard = (db: Database, jwtSecret: string, path: string) => async (c: Context, next: Next) => {
  const token = getCookie(c, "session");
  if (!token) return c.redirect("/auth");
  try {
    const claims = await verify(token, jwtSecret, "HS256") as { sub: string; role_id: number };
    const basePath = path.match(/^\/dashboard\/admin\/[^/]+/)?.[0] ?? path;
    if (!createPermissionChecker(db)(claims.role_id, path) && !createPermissionChecker(db)(claims.role_id, basePath)) return c.html(<p class="alert alert-error">Forbidden</p>, 403);
    c.set("auth", claims); return next();
  } catch { return c.redirect("/auth"); }
};

export function createAdminRoutes(db: Database, jwtSecret = process.env.JWT_SECRET ?? "development-secret") {
  const app = new Hono();
  const page = (c: Context, title: string, body: any) => { const auth = c.get("auth") as { role_id: number; sub: string }; const allowed = db.query<{ title: string }, [number]>("SELECT e.title FROM endpoints e JOIN role_endpoints re ON re.endpoint_id=e.id WHERE re.role_id=? AND e.deleted_at IS NULL AND re.deleted_at IS NULL").all(auth.role_id).map((r) => r.title); const user = db.query<{ name: string; email: string; role: string }, [number]>("SELECT COALESCE(NULLIF(TRIM(first_name||' '||last_name),''),COALESCE(username,email)) name,email,r.title role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=?").get(Number(auth.sub)) ?? undefined; return c.html(<AdminLayout allowed={allowed} title={title} user={user}>{body}</AdminLayout>); };
  app.use("*", async (c, next) => guard(db, jwtSecret, c.req.path)(c, next));
  app.get("/", (c) => c.redirect("/dashboard/admin/users"));
  const config = {
    users: { table: "users", columns: ["id", "email", "username", "phone", "first_name", "last_name", "role_id", "created_at", "updated_at"], fields: ["email", "username", "phone", "first_name", "last_name", "password", "role_id"] },
    meets: { table: "meets", columns: ["id", "title", "topics", "scheduled_date", "scheduled_time", "duration_minutes", "meet_url", "image_url", "presenter_id", "created_at", "updated_at"], fields: ["title", "topics", "scheduled_date", "scheduled_time", "duration_minutes", "meet_url", "image_url", "presenter_id"] },
    tags: { table: "tags", columns: ["id", "title", "description", "created_at", "updated_at"], fields: ["title", "description"] },
    roles: { table: "roles", columns: ["id", "title", "description", "created_at", "updated_at"], fields: ["title", "description"] },
    endpoints: { table: "endpoints", columns: ["id", "title", "description", "created_at", "updated_at"], fields: ["title", "description"] },
  } as const;
  const form = (resource: keyof typeof config, id?: number, values: Row = {}) => {
    const roles = db.query<{ id: number; title: string }, []>("SELECT id,title FROM roles WHERE deleted_at IS NULL ORDER BY title").all();
    const users = db.query<{ id: number; email: string }, []>("SELECT id,email FROM users WHERE deleted_at IS NULL ORDER BY email").all();
    const inputType = (field: string) => field === "password" ? "password" : field.includes("date") ? "date" : field.includes("time") ? "time" : field === "duration_minutes" ? "number" : field.endsWith("_url") ? "url" : "text";
    return <dialog id="record-modal" class="modal modal-open"><div class="modal-box max-w-2xl"><h3 class="font-bold text-lg">{id ? "Edit" : "Add"} {resource}</h3><form hx-post={`/dashboard/admin/${resource}${id ? `/${id}` : ""}`} hx-target={`#${resource}-table`} hx-swap="outerHTML" class="grid gap-3 mt-4 sm:grid-cols-2">{config[resource].fields.map((field) => <label class="form-control"><span class="label-text">{field.replaceAll("_", " ")}</span>{field === "role_id" ? <select class="select select-bordered" name={field} required value={String(values[field] ?? "")}><option value="">Choose role</option>{roles.map((role) => <option value={String(role.id)}>{role.title}</option>)}</select> : field === "presenter_id" ? <select class="select select-bordered" name={field} value={String(values[field] ?? "")}><option value="">Free discussion</option>{users.map((user) => <option value={String(user.id)}>{user.email}</option>)}</select> : <input class="input input-bordered" name={field} type={inputType(field)} value={field === "password" ? "" : String(values[field] ?? "")} required={field === "title" || field === "email" || field === "scheduled_date" || field === "scheduled_time" || (!id && field === "password")} />}</label>)}<div class="modal-action sm:col-span-2"><button type="button" class="btn" onclick="this.closest('dialog').remove()">Cancel</button><button class="btn btn-primary">Save</button></div></form></div></dialog>;
  };
  const toast = (title: string, fallback: string) => { const message = getErrorMessage(title); return <Toast type={message.type} title={message.title} description={message.description || fallback} />; };
  for (const resource of Object.keys(config) as (keyof typeof config)[]) {
    const { table, columns, fields } = config[resource];
    app.get(`/${resource}`, (c) => page(c, resource, <CrudTable resource={resource} columns={[...columns]} rows={db.query(`SELECT id, ${columns.join(", ")} FROM ${table} WHERE deleted_at IS NULL ORDER BY id DESC`).all() as Row[]} />));
    app.get(`/${resource}/new`, (c) => c.html(form(resource)));
    app.get(`/${resource}/:id/edit`, (c) => { const editable = resource === "users" ? fields.filter((field) => field !== "password") : fields; const row = db.query(`SELECT ${editable.join(", ")} FROM ${table} WHERE id=? AND deleted_at IS NULL`).get(Number(c.req.param("id"))) as Row | null; return row ? c.html(form(resource, Number(c.req.param("id")), row)) : c.notFound(); });
    app.get(`/${resource}/:id/confirm`, (c) => c.html(<dialog class="modal modal-open"><div class="modal-box"><h3 class="font-bold">Delete {resource}?</h3><p class="py-4">This item will be removed from active results.</p><form hx-delete={`/dashboard/admin/${resource}/${c.req.param("id")}`} hx-target={`#${resource}-table`} hx-swap="outerHTML"><button class="btn btn-error">Delete</button><button type="button" class="btn" onclick="this.closest('dialog').remove()">Cancel</button></form></div></dialog>));
    app.post(`/${resource}`, async (c) => { const body = await c.req.parseBody(); if (resource === "users") { const password = String(body.password ?? ""); if (!password) return c.html(toast("admin.created", "Password is required."), 400); const fields = config.users.fields.filter((field) => field !== "password"); const values = fields.map((field) => String(body[field] ?? "").trim() || null); db.run(`INSERT INTO users (${fields.join(",")},password_hash) VALUES (${fields.map(() => "?").join(",")},?)`, [...values, await Bun.password.hash(password)]); } else { const values = fields.map((field) => String(body[field] ?? "").trim() || null); db.run(`INSERT INTO ${table} (${fields.join(",")}) VALUES (${fields.map(() => "?").join(",")})`, values); } return c.html(<><CrudTable resource={resource} columns={[...columns]} rows={db.query(`SELECT ${columns.join(", ")} FROM ${table} WHERE deleted_at IS NULL ORDER BY id DESC`).all() as Row[]} />{toast("admin.created", "Created")}</>); });
    app.post(`/${resource}/:id`, async (c) => { const body = await c.req.parseBody(); if (resource === "users") { const fields = config.users.fields.filter((field) => field !== "password"); const values = fields.map((field) => String(body[field] ?? "").trim() || null); const password = String(body.password ?? ""); db.run(`UPDATE users SET ${fields.map((field) => `${field}=?`).join(",")}${password ? ",password_hash=?" : ""},updated_at=CURRENT_TIMESTAMP WHERE id=?`, [...values, ...(password ? [await Bun.password.hash(password)] : []), Number(c.req.param("id"))]); } else { const values = fields.map((field) => String(body[field] ?? "").trim() || null); db.run(`UPDATE ${table} SET ${fields.map((field) => `${field}=?`).join(",")}, updated_at=CURRENT_TIMESTAMP WHERE id=?`, [...values, Number(c.req.param("id"))]); } return c.html(<CrudTable resource={resource} columns={[...columns]} rows={db.query(`SELECT ${columns.join(", ")} FROM ${table} WHERE deleted_at IS NULL ORDER BY id DESC`).all() as Row[]}/>); });
    app.delete(`/${resource}/:id`, (c) => { const id = Number(c.req.param("id")); if (resource === "roles" && db.query("SELECT 1 FROM roles WHERE id=? AND title='Super Admin'").get(id)) return c.html(toast("admin.super_admin_protected", "Protected"), 403); db.run(`UPDATE ${table} SET deleted_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=?`, [id]); return c.html(<><CrudTable resource={resource} columns={[...columns]} rows={db.query(`SELECT id, ${columns.join(", ")} FROM ${table} WHERE deleted_at IS NULL ORDER BY id DESC`).all() as Row[]}/>{toast("admin.deleted", "Deleted")}</>); });
    app.post(`/${resource}/bulk-delete`, async (c) => { const body = await c.req.parseBody(); const ids = (Array.isArray(body.ids) ? body.ids : [body.ids]).filter(Boolean).map(Number); for (const id of ids) if (!(resource === "roles" && db.query("SELECT 1 FROM roles WHERE id=? AND title='Super Admin'").get(id))) db.run(`UPDATE ${table} SET deleted_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=?`, [id]); return c.html(toast("admin.deleted", "Deleted")); });
  }
  app.post("/roles/:id/endpoints", async (c) => { const roleId = Number(c.req.param("id")); const endpointId = Number((await c.req.parseBody()).endpoint_id); if (!db.query("SELECT 1 FROM endpoints WHERE id=? AND deleted_at IS NULL").get(endpointId)) return c.html(<p class="alert alert-error">Invalid endpoint.</p>, 400); if (db.query("SELECT 1 FROM roles WHERE id=? AND title='Super Admin'").get(roleId)) return c.html(<p class="alert alert-error">The Super Admin role is managed by the system.</p>, 403); db.run("INSERT OR IGNORE INTO role_endpoints (role_id,endpoint_id,description) VALUES (?,?,?)", [roleId, endpointId, "Assigned by admin"]); return c.html(<p class="alert alert-success">Endpoint assigned.</p>); });
  app.get("/roles/:id/endpoints/new", (c) => c.html(<form class="flex gap-2" hx-post={`/dashboard/admin/roles/${c.req.param("id")}/endpoints`} hx-target="this"><select name="endpoint_id" class="select select-bordered">{db.query<{ id: number; title: string }, []>("SELECT id,title FROM endpoints WHERE deleted_at IS NULL ORDER BY title").all().map((endpoint) => <option value={String(endpoint.id)}>{endpoint.title}</option>)}</select><button class="btn btn-primary">Assign endpoint</button></form>));
  app.get("/endpoints", (c) => page(c, "Endpoints", <CrudTable resource="endpoints" columns={["title", "description"]} rows={db.query("SELECT id,title,description FROM endpoints WHERE deleted_at IS NULL ORDER BY title").all() as Row[]} />));
  app.get("/reports/users", (c) => page(c, "Full Users Report", <CrudTable resource="users" columns={["email", "username", "first_name", "last_name", "role_id"]} rows={db.query("SELECT id,email,username,first_name,last_name,role_id FROM users WHERE deleted_at IS NULL").all() as Row[]} />));
  app.get("/reports/meets", (c) => page(c, "Full Meets Report", <CrudTable resource="meets" columns={["title", "scheduled_date", "scheduled_time", "duration_minutes"]} rows={db.query("SELECT id,title,scheduled_date,scheduled_time,duration_minutes FROM meets WHERE deleted_at IS NULL").all() as Row[]} />));
  return app;
}
