import { Layout } from "../../ui/layout";

export type Row = Record<string, string | number | null>;
const links = [["Users", "/dashboard/admin/users"], ["Meets", "/dashboard/admin/meets"], ["Tags", "/dashboard/admin/tags"], ["Roles", "/dashboard/admin/roles"], ["Endpoints", "/dashboard/admin/endpoints"], ["User report", "/dashboard/admin/reports/users"], ["Meet report", "/dashboard/admin/reports/meets"]] as const;

export function AdminLayout({ children, allowed, title = "Admin", user }: { children: any; allowed: string[]; title?: string; user?: { name: string; email: string; role: string } }) {
  return <Layout title={title}><div class="drawer lg:drawer-open bg-base-200 min-h-screen"><input id="admin-drawer" type="checkbox" class="drawer-toggle" /><div class="drawer-content"><nav class="navbar min-h-16 bg-base-100 border-b px-4 shadow-sm sm:px-8"><label for="admin-drawer" class="btn btn-square btn-ghost lg:hidden">☰</label><a href="/dashboard/admin" class="flex-1 text-xl font-bold">Meetspace Admin</a><div class="flex items-center gap-2"><a href="/dashboard/member" class="btn btn-ghost btn-sm">Back to app</a>{user && <div class="dropdown dropdown-end"><button class="btn btn-ghost btn-sm gap-2" tabindex={0}><div class="avatar placeholder"><div class="w-8 rounded-full bg-primary text-primary-content"><span>{user.name[0]?.toUpperCase()}</span></div></div><span class="hidden text-left sm:block"><span class="block text-xs font-semibold">{user.name}</span><span class="block text-xs opacity-60">{user.role}</span></span></button><div class="card dropdown-content z-20 mt-3 w-64 border border-base-300 bg-base-100 shadow-xl" tabindex={0}><div class="card-body gap-2 p-4"><p class="font-semibold">{user.name}</p><p class="text-sm opacity-60">{user.email}</p><form hx-post="/auth/logout" class="mt-2"><button class="btn btn-error btn-outline btn-sm w-full" type="submit">Sign out</button></form></div></div></div>}</div></nav><main class="p-4 md:p-8 max-w-7xl mx-auto">{children}</main></div><aside class="drawer-side"><label for="admin-drawer" class="drawer-overlay" /><ul class="menu p-4 w-72 min-h-full bg-base-100"><li class="menu-title">Base info</li>{links.slice(0, 5).filter(([, href]) => allowed.includes(href)).map(([label, href]) => <li><a href={href}>{label}</a></li>)}<li class="menu-title mt-4">Reports</li>{links.slice(5).filter(([, href]) => allowed.includes(href)).map(([label, href]) => <li><a href={href}>{label}</a></li>)}</ul></aside></div></Layout>;
}

export function CrudTable({ resource, rows, columns }: { resource: string; rows: Row[]; columns: string[] }) {
  return <div id={`${resource}-table`}><div class="flex justify-between items-center mb-4"><h1 class="text-2xl font-bold capitalize">{resource}</h1><div class="flex gap-2"><button class="btn btn-primary btn-sm" hx-get={`/dashboard/admin/${resource}/new`} hx-target="#modal">Add new</button><button class="btn btn-error btn-sm" hx-post={`/dashboard/admin/${resource}/bulk-delete`} hx-include="#bulk-action-form" hx-target="#toast-container">Delete selected</button></div></div><form id="bulk-action-form"><div class="overflow-x-auto bg-base-100 rounded-box shadow"><table class="table"><thead><tr><th></th>{columns.map((column) => <th>{column}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr id={`${resource}-${row.id}`}><td><input type="checkbox" name="ids" value={String(row.id)} class="checkbox" /></td>{columns.map((column) => <td>{String(row[column] ?? "—")}</td>)}<td class="flex gap-2"><button type="button" class="btn btn-xs" hx-get={`/dashboard/admin/${resource}/${row.id}/edit`} hx-target="#modal">Edit</button><button type="button" class="btn btn-xs btn-error" hx-get={`/dashboard/admin/${resource}/${row.id}/confirm`} hx-target="#modal">Delete</button></td></tr>)}</tbody></table></div></form><div id="modal"></div></div>;
}

export const Toast = ({ type, title, description }: { type: string; title: string; description: string }) => <div class={`alert alert-${type}`} hx-swap-oob="beforeend:#toast-container"><span><strong>{title}</strong> {description}</span></div>;
