import { Layout } from "../../ui/layout";

export type Row = Record<string, string | number | null>;
const links = [["Users", "/dashboard/admin/users"], ["Meets", "/dashboard/admin/meets"], ["Tags", "/dashboard/admin/tags"], ["Roles", "/dashboard/admin/roles"], ["Endpoints", "/dashboard/admin/endpoints"], ["User report", "/dashboard/admin/reports/users"], ["Meet report", "/dashboard/admin/reports/meets"]] as const;

export function AdminLayout({ children, allowed, title = "Admin" }: { children: any; allowed: string[]; title?: string }) {
  return <Layout title={title}><div class="drawer lg:drawer-open bg-base-200 min-h-screen"><input id="admin-drawer" type="checkbox" class="drawer-toggle" /><div class="drawer-content"><nav class="navbar bg-base-100 border-b px-4"><label for="admin-drawer" class="btn btn-square btn-ghost lg:hidden">☰</label><a href="/dashboard/admin" class="text-xl font-bold">Meetspace Admin</a><div class="ml-auto"><a href="/dashboard" class="btn btn-ghost btn-sm">Back to app</a><a href="/auth/logout" class="btn btn-sm">Sign out</a></div></nav><main class="p-4 md:p-8 max-w-7xl mx-auto">{children}</main></div><aside class="drawer-side"><label for="admin-drawer" class="drawer-overlay" /><ul class="menu p-4 w-72 min-h-full bg-base-100"><li class="menu-title">Base info</li>{links.slice(0, 5).filter(([, href]) => allowed.includes(href)).map(([label, href]) => <li><a href={href}>{label}</a></li>)}<li class="menu-title mt-4">Reports</li>{links.slice(5).filter(([, href]) => allowed.includes(href)).map(([label, href]) => <li><a href={href}>{label}</a></li>)}</ul></aside></div></Layout>;
}

export function CrudTable({ resource, rows, columns }: { resource: string; rows: Row[]; columns: string[] }) {
  return <form id="bulk-action-form" hx-post={`/dashboard/admin/${resource}/bulk-delete`} hx-target="#table-result"><div class="flex justify-between items-center mb-4"><h1 class="text-2xl font-bold capitalize">{resource}</h1><button class="btn btn-error btn-sm" hx-confirm="Delete selected items?">Delete selected</button></div><div id="table-result" class="overflow-x-auto bg-base-100 rounded-box shadow"><table class="table"><thead><tr><th></th>{columns.map((column) => <th>{column}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr><td><input type="checkbox" name="ids" value={String(row.id)} class="checkbox" /></td>{columns.map((column) => <td>{String(row[column] ?? "—")}</td>)}<td class="flex gap-2"><button type="button" class="btn btn-xs" hx-get={`/dashboard/admin/${resource}/${row.id}/edit`} hx-target="#modal">Edit</button><button type="button" class="btn btn-xs btn-error" hx-delete={`/dashboard/admin/${resource}/${row.id}`} hx-confirm="Delete this item?" hx-target="closest tr" hx-swap="outerHTML">Delete</button></td></tr>)}</tbody></table></div><div id="modal"></div></form>;
}
