import type { LandingCache } from "../../lib/cache";

export const Landing = ({ data }: { data: LandingCache }) => (
  <div>
    <nav class="navbar absolute z-10 px-6 text-white sm:px-12"><div class="flex-1 text-2xl font-bold">Meetspace</div><div class="flex-none gap-3"><a class="btn btn-ghost btn-sm" href="/auth">Sign in</a><a class="btn btn-ghost btn-sm" href="#about">About us</a></div></nav>
    <section class="hero min-h-[34rem] bg-[url('https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1800&q=80')] bg-cover bg-center"><div class="hero-overlay bg-black/65"></div><div class="hero-content z-0 w-full max-w-6xl justify-between px-6 py-28 text-neutral-content sm:px-12"><div class="max-w-xl"><p class="mb-4 font-semibold text-primary">Learn together, in person or online</p><h1 class="text-5xl font-bold leading-tight sm:text-6xl">Good conversations start with a shared room.</h1><p class="mt-6 text-lg text-neutral-content/80">Find thoughtful people, practical topics, and the next meet worth attending.</p></div><a class="btn btn-primary btn-lg mt-10 self-end" href="#meets">What&apos;s next</a></div></section>
    <section class="bg-base-100 py-6"><div class="stats stats-vertical mx-auto flex max-w-5xl rounded-box shadow sm:stats-horizontal"><div class="stat"><div class="stat-title">Total Users</div><div class="stat-value text-primary">{data.totalUsers}</div></div><div class="stat"><div class="stat-title">Total Hours of Meets</div><div class="stat-value text-secondary">{data.totalMeetHours}</div></div></div></section>
    <section id="about" class="container mx-auto grid max-w-6xl gap-8 px-6 py-20 lg:grid-cols-2"><img class="h-72 w-full rounded-box object-cover shadow-xl" src="https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1000&q=80" alt="People meeting" /><div class="card bg-base-100 shadow-xl"><div class="card-body justify-center"><p class="font-semibold text-primary">Built for meaningful meets</p><h2 class="card-title text-3xl">One room. Many perspectives.</h2><p>Meetspace makes it easy to discover focused conversations and show up prepared to learn.</p></div></div></section>
    <section id="meets" class="bg-base-200 py-20"><div class="container mx-auto max-w-6xl px-6"><h2 class="text-3xl font-bold">Upcoming meets</h2><div class="carousel mt-8 w-full gap-5 rounded-box pb-4">{data.meets.length ? data.meets.map((meet) => <article class="carousel-item group relative h-80 w-72 overflow-hidden rounded-box bg-base-300 shadow-xl"><img class="h-full w-full object-cover transition duration-500 group-hover:scale-110" src={meet.image_url ?? "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=700&q=80"} alt={meet.title} /><div class="absolute inset-0 flex translate-y-full flex-col justify-end bg-gradient-to-t from-black via-black/70 to-transparent p-6 text-white transition duration-300 group-hover:translate-y-0"><h3 class="text-xl font-bold">{meet.title}</h3><p class="mt-2 text-sm">{meet.topics.join(" · ") || "Open discussion"}</p><p class="mt-4 text-sm opacity-80">{meet.scheduled_date} · {meet.scheduled_time}</p></div></article>) : <div class="rounded-box border border-dashed border-base-300 bg-base-100 p-10 text-base-content/60">No upcoming meets yet.</div>}</div></div></section>
    <footer class="footer bg-neutral p-10 text-neutral-content"><aside><p class="text-xl font-bold">Meetspace</p><p>Conversations worth making time for.</p></aside><nav><h6 class="footer-title">Find us</h6><a href="mailto:hello@example.com" class="link link-hover">Email</a><a href="#" class="link link-hover">Telegram</a><a href="#" class="link link-hover">GitHub</a><a href="#" class="link link-hover">LinkedIn</a></nav><form class="w-full max-w-xs" hx-post="/api/contact" hx-swap="outerHTML"><h6 class="footer-title">Want to contact?</h6><fieldset class="form-control"><input class="input input-bordered text-base-content" name="email" type="email" required placeholder="you@example.com" /><button class="btn btn-primary mt-3">Send</button></fieldset></form></footer>
  </div>
);
